### PR TITLE
Remove sdk as a dev dependency

### PR DESCRIPTION
**Pull request by joewagner**
The `@tableland/sdk` package is a devDep of this package in order to do integration testing, but once the `@tableland/local` package exports all of its testing helpers in https://github.com/tablelandnetwork/local-tableland/pull/196 we will no longer need the sdk as a devDep.

This should help alleviate some of our circular package dep concerns.

NOTE: this pr won't work until https://github.com/tablelandnetwork/local-tableland/pull/196 is published

### CODE REVIEW

**Review by carsonfarmer — DISMISSED** [review]
Fantastic! Super good idea @joewagner, I love this. And pleased that it was actually a relatively simple fix in the end. Nice work.

**Comment by joewagner** [comment]
> Fantastic! Super good idea @joewagner, I love this. And pleased that it was actually a relatively simple fix in the end. Nice work.

Thanks!  I'll publish local now then once this is merged and published we won't have anymore circular packaging in `dependencies`

**Comment by joewagner** [comment]
@carsonfarmer local was published and tests are passing

**Review by carsonfarmer — APPROVED** [review]
excellent!

**Pull request merged**
