### PR TITLE
add support for Sepolia

### PR DESCRIPTION
**Pull request by sanderpick**
Adds support for Sepolia.
Drops supprot for Goerli. 

Fixes EVM-38
Fixes EVM-39

### CODE REVIEW

**Review by joewagner — APPROVED** [review]
Looks good!

**Comment by sanderpick** [comment]
Hmm, I can't seem to get the tests to pass... re-ran four times.

**Comment by avichalp** [comment]
It seems like the hardhat node is not running when the deployment script is executed. 

```sh
HardhatError: HH108: Cannot connect to the network localhost.
Please make sure your node is running, and check your internet connection and networks config
```
and 

```sh
Caused by: Error: connect ECONNREFUSED 127.0.0.1:8545 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

The same thing works fine locally. Could it be that the hardhat node is not spinning up before the script starts running? Maybe we can add `sleep` in between?

```sh
  npx hardhat node &
  sleep 5
  npx hardhat run scripts/deploy.ts --network localhost  
```

**Comment by joewagner** [comment]
> Hmm, I can't seem to get the tests to pass... re-ran four times.

I created an issue to capture this work, but maybe we should prioritize it.  I can work on it the coming week.

**Comment by joewagner** [comment]
@sanderpick I _might_ have found the problem with the tests.  I can't be sure since it's only showing up in the gh actions.  hardhat unit tests node might be causing problems starting the local-tableland test network.  I changed the order of the test running, and everything seems to work, but it could just be coincidence.
Either way, this PR is gtg now

**Comment by sanderpick** [comment]
no need to upgrade... the deployed contract is already up to date with main.

**Review by awmuncy — APPROVED** [review]
LGTM

**Pull request merged**
